// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHealthcareSystem.Data;

#nullable disable

namespace HealthcareSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251216173500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartHealthcareSystem.Models.AIConversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationId"));

                    b.Property<string>("AIResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecommendedMedicines")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("AIConversations");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Disease", b =>
                {
                    b.Property<int>("DiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiseaseId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiseaseId");

                    b.ToTable("Diseases");

                    b.HasData(
                        new
                        {
                            DiseaseId = 1,
                            Description = "A viral infection of the upper respiratory tract",
                            Name = "Common Cold",
                            NameArabic = "نزلة برد",
                            Severity = "Mild",
                            Symptoms = "fever,cough,sore throat,runny nose,headache,حمى,سعال,التهاب حلق,صداع"
                        },
                        new
                        {
                            DiseaseId = 2,
                            Description = "A contagious respiratory illness caused by influenza viruses",
                            Name = "Influenza",
                            NameArabic = "إنفلونزا",
                            Severity = "Moderate",
                            Symptoms = "high fever,body ache,fatigue,headache,cough,حمى شديدة,ألم جسم,تعب,صداع,سعال"
                        },
                        new
                        {
                            DiseaseId = 3,
                            Description = "Pain in any region of the head",
                            Name = "Headache",
                            NameArabic = "صداع",
                            Severity = "Mild",
                            Symptoms = "head pain,migraine,tension,صداع,ألم رأس,شقيقة"
                        },
                        new
                        {
                            DiseaseId = 4,
                            Description = "Inflammation of the stomach lining",
                            Name = "Gastritis",
                            NameArabic = "التهاب المعدة",
                            Severity = "Moderate",
                            Symptoms = "stomach pain,nausea,vomiting,bloating,ألم معدة,غثيان,قيء,انتفاخ"
                        });
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DoctorId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<string>("ActiveIngredient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MedicineId");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            MedicineId = 1,
                            ActiveIngredient = "Paracetamol",
                            Category = "Pain Relief",
                            Description = "Effective for pain relief and fever reduction",
                            DosageForm = "Tablets",
                            GenericName = "Acetaminophen",
                            ImageUrl = "/images/medicines/paracetamol.jpg",
                            IsAvailable = true,
                            Name = "Paracetamol",
                            Price = 3.50m,
                            Strength = "500mg"
                        },
                        new
                        {
                            MedicineId = 2,
                            ActiveIngredient = "Ibuprofen",
                            Category = "Pain Relief",
                            Description = "Anti-inflammatory and pain relief",
                            DosageForm = "Tablets",
                            GenericName = "Ibuprofen",
                            ImageUrl = "/images/medicines/ibuprofen.jpg",
                            IsAvailable = true,
                            Name = "Ibuprofen",
                            Price = 5.00m,
                            Strength = "400mg"
                        },
                        new
                        {
                            MedicineId = 3,
                            ActiveIngredient = "Amoxicillin",
                            Category = "Antibiotics",
                            Description = "Antibiotic for bacterial infections",
                            DosageForm = "Capsules",
                            GenericName = "Amoxicillin",
                            ImageUrl = "/images/medicines/amoxicillin.jpg",
                            IsAvailable = true,
                            Name = "Amoxicillin",
                            Price = 8.50m,
                            Strength = "500mg"
                        },
                        new
                        {
                            MedicineId = 4,
                            ActiveIngredient = "Omeprazole",
                            Category = "Digestive Health",
                            Description = "For stomach acid and heartburn",
                            DosageForm = "Capsules",
                            GenericName = "Omeprazole",
                            ImageUrl = "/images/medicines/omeprazole.jpg",
                            IsAvailable = true,
                            Name = "Omeprazole",
                            Price = 6.00m,
                            Strength = "20mg"
                        },
                        new
                        {
                            MedicineId = 5,
                            ActiveIngredient = "Cetirizine",
                            Category = "Allergy Relief",
                            Description = "Antihistamine for allergies",
                            DosageForm = "Tablets",
                            GenericName = "Cetirizine",
                            ImageUrl = "/images/medicines/cetirizine.jpg",
                            IsAvailable = true,
                            Name = "Cetirizine",
                            Price = 4.00m,
                            Strength = "10mg"
                        });
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.TreatmentRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiseaseId")
                        .HasColumnType("int");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("MedicineId");

                    b.ToTable("TreatmentRecommendations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiseaseId = 1,
                            MedicineId = 1,
                            Priority = 9
                        },
                        new
                        {
                            Id = 2,
                            DiseaseId = 1,
                            MedicineId = 5,
                            Priority = 7
                        },
                        new
                        {
                            Id = 3,
                            DiseaseId = 2,
                            MedicineId = 1,
                            Priority = 10
                        },
                        new
                        {
                            Id = 4,
                            DiseaseId = 2,
                            MedicineId = 2,
                            Priority = 8
                        },
                        new
                        {
                            Id = 5,
                            DiseaseId = 3,
                            MedicineId = 1,
                            Priority = 9
                        },
                        new
                        {
                            Id = 6,
                            DiseaseId = 3,
                            MedicineId = 2,
                            Priority = 8
                        },
                        new
                        {
                            Id = 7,
                            DiseaseId = 4,
                            MedicineId = 4,
                            Priority = 10
                        });
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 12, 16, 20, 34, 59, 709, DateTimeKind.Local).AddTicks(9713),
                            Email = "admin@healthcare.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$QlVs2d5ZhjA.BKCSa6q7DuJi9208bR9ue/NZnwb9whowD7L1grJt6",
                            Phone = "0790000000",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.AIConversation", b =>
                {
                    b.HasOne("SmartHealthcareSystem.Models.User", "User")
                        .WithMany("AIConversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Appointment", b =>
                {
                    b.HasOne("SmartHealthcareSystem.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartHealthcareSystem.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Doctor", b =>
                {
                    b.HasOne("SmartHealthcareSystem.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("SmartHealthcareSystem.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Patient", b =>
                {
                    b.HasOne("SmartHealthcareSystem.Models.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("SmartHealthcareSystem.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.TreatmentRecommendation", b =>
                {
                    b.HasOne("SmartHealthcareSystem.Models.Disease", "Disease")
                        .WithMany("TreatmentRecommendations")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHealthcareSystem.Models.Medicine", "Medicine")
                        .WithMany("TreatmentRecommendations")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Disease", b =>
                {
                    b.Navigation("TreatmentRecommendations");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Medicine", b =>
                {
                    b.Navigation("TreatmentRecommendations");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.User", b =>
                {
                    b.Navigation("AIConversations");

                    b.Navigation("Doctor")
                        .IsRequired();

                    b.Navigation("Patient")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
