// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHealthcareSystem.Data;

#nullable disable

namespace HealthcareSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260131192703_UpdateAIConversationOptionalFields")]
    partial class UpdateAIConversationOptionalFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartHealthcareSystem.Models.AIConversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationId"));

                    b.Property<string>("AIResponse")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<double?>("Confidence")
                        .HasColumnType("float");

                    b.Property<string>("DiseaseName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecommendedMedicines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("AIConversations");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Disease", b =>
                {
                    b.Property<int>("DiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiseaseId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiseaseId");

                    b.ToTable("Diseases");

                    b.HasData(
                        new
                        {
                            DiseaseId = 1,
                            Description = "فيروس يصيب الجهاز التنفسي العلوي",
                            Name = "Common Cold",
                            NameArabic = "نزلة برد",
                            Severity = "Mild",
                            Symptoms = "fever,cough,sore throat,runny nose,headache,sneezing,congestion,حمى,سعال,التهاب حلق,رشح,صداع,عطس,احتقان"
                        },
                        new
                        {
                            DiseaseId = 2,
                            Description = "عدوى فيروسية تصيب الجهاز التنفسي",
                            Name = "Influenza",
                            NameArabic = "إنفلونزا",
                            Severity = "Moderate",
                            Symptoms = "high fever,body ache,fatigue,headache,cough,chills,weakness,حمى شديدة,ألم جسم,تعب,صداع,سعال,قشعريرة,ضعف"
                        },
                        new
                        {
                            DiseaseId = 3,
                            Description = "التهاب في بطانة الشعب الهوائية",
                            Name = "Bronchitis",
                            NameArabic = "التهاب الشعب الهوائية",
                            Severity = "Moderate",
                            Symptoms = "cough,mucus,chest discomfort,fatigue,shortness of breath,سعال,بلغم,ألم صدر,تعب,ضيق تنفس"
                        },
                        new
                        {
                            DiseaseId = 4,
                            Description = "عدوى تسبب التهاب في الرئتين",
                            Name = "Pneumonia",
                            NameArabic = "التهاب رئوي",
                            Severity = "Severe",
                            Symptoms = "fever,cough,chest pain,shortness of breath,fatigue,chills,حمى,سعال,ألم صدر,ضيق تنفس,تعب,قشعريرة"
                        },
                        new
                        {
                            DiseaseId = 5,
                            Description = "مرض مزمن يصيب الشعب الهوائية",
                            Name = "Asthma",
                            NameArabic = "الربو",
                            Severity = "Moderate",
                            Symptoms = "wheezing,shortness of breath,chest tightness,cough,صفير,ضيق تنفس,ضيق صدر,سعال"
                        },
                        new
                        {
                            DiseaseId = 6,
                            Description = "التهاب في بطانة المعدة",
                            Name = "Gastritis",
                            NameArabic = "التهاب المعدة",
                            Severity = "Moderate",
                            Symptoms = "stomach pain,nausea,vomiting,bloating,loss of appetite,ألم معدة,غثيان,قيء,انتفاخ,فقدان شهية"
                        },
                        new
                        {
                            DiseaseId = 7,
                            Description = "مرض ناتج عن تناول طعام ملوث",
                            Name = "Food Poisoning",
                            NameArabic = "تسمم غذائي",
                            Severity = "Moderate",
                            Symptoms = "nausea,vomiting,diarrhea,stomach cramps,fever,weakness,غثيان,قيء,إسهال,مغص,حمى,ضعف"
                        },
                        new
                        {
                            DiseaseId = 8,
                            Description = "التهاب في المعدة والأمعاء",
                            Name = "Gastroenteritis",
                            NameArabic = "التهاب معوي",
                            Severity = "Moderate",
                            Symptoms = "diarrhea,vomiting,stomach pain,fever,dehydration,إسهال,قيء,ألم معدة,حمى,جفاف"
                        },
                        new
                        {
                            DiseaseId = 9,
                            Description = "صعوبة في حركة الأمعاء",
                            Name = "Constipation",
                            NameArabic = "إمساك",
                            Severity = "Mild",
                            Symptoms = "difficult bowel movement,abdominal pain,bloating,صعوبة إخراج,ألم بطن,انتفاخ"
                        },
                        new
                        {
                            DiseaseId = 10,
                            Description = "ارتداد حمض المعدة إلى المريء",
                            Name = "Acid Reflux",
                            NameArabic = "ارتجاع المريء",
                            Severity = "Moderate",
                            Symptoms = "heartburn,chest pain,difficulty swallowing,sour taste,حرقة,ألم صدر,صعوبة بلع,طعم حامض"
                        },
                        new
                        {
                            DiseaseId = 11,
                            Description = "ألم في منطقة الرأس",
                            Name = "Headache",
                            NameArabic = "صداع",
                            Severity = "Mild",
                            Symptoms = "head pain,pressure,throbbing,sensitivity to light,صداع,ضغط رأس,ألم نابض,حساسية ضوء"
                        },
                        new
                        {
                            DiseaseId = 12,
                            Description = "صداع شديد ومتكرر",
                            Name = "Migraine",
                            NameArabic = "شقيقة",
                            Severity = "Moderate",
                            Symptoms = "severe headache,nausea,vomiting,sensitivity to light,visual disturbances,صداع شديد,غثيان,قيء,حساسية ضوء,اضطراب رؤية"
                        },
                        new
                        {
                            DiseaseId = 13,
                            Description = "ألم في منطقة الظهر",
                            Name = "Back Pain",
                            NameArabic = "ألم الظهر",
                            Severity = "Moderate",
                            Symptoms = "back pain,stiffness,muscle ache,limited movement,ألم ظهر,تيبس,ألم عضلي,صعوبة حركة"
                        },
                        new
                        {
                            DiseaseId = 14,
                            Description = "التهاب الأنف التحسسي",
                            Name = "Allergic Rhinitis",
                            NameArabic = "حساسية الأنف",
                            Severity = "Mild",
                            Symptoms = "sneezing,runny nose,itchy eyes,congestion,عطس,رشح,حكة عين,احتقان"
                        },
                        new
                        {
                            DiseaseId = 15,
                            Description = "رد فعل تحسسي على الجلد",
                            Name = "Skin Allergy",
                            NameArabic = "حساسية جلدية",
                            Severity = "Mild",
                            Symptoms = "rash,itching,redness,swelling,hives,طفح,حكة,احمرار,تورم,شرى"
                        },
                        new
                        {
                            DiseaseId = 16,
                            Description = "عدوى في الجهاز البولي",
                            Name = "Urinary Tract Infection",
                            NameArabic = "التهاب مجرى البول",
                            Severity = "Moderate",
                            Symptoms = "burning urination,frequent urination,cloudy urine,pelvic pain,حرقة بول,تبول متكرر,بول عكر,ألم حوض"
                        },
                        new
                        {
                            DiseaseId = 17,
                            Description = "التهاب في الأذن الوسطى",
                            Name = "Ear Infection",
                            NameArabic = "التهاب الأذن",
                            Severity = "Moderate",
                            Symptoms = "ear pain,fever,drainage,hearing difficulty,ألم أذن,حمى,إفرازات,صعوبة سمع"
                        },
                        new
                        {
                            DiseaseId = 18,
                            Description = "التهاب الجيوب الأنفية",
                            Name = "Sinusitis",
                            NameArabic = "التهاب الجيوب الأنفية",
                            Severity = "Moderate",
                            Symptoms = "facial pain,nasal congestion,headache,mucus,pressure,ألم وجه,احتقان أنف,صداع,مخاط,ضغط"
                        },
                        new
                        {
                            DiseaseId = 19,
                            Description = "حالة جلدية مزمنة",
                            Name = "Eczema",
                            NameArabic = "أكزيما",
                            Severity = "Mild",
                            Symptoms = "dry skin,itching,redness,rash,cracked skin,جلد جاف,حكة,احمرار,طفح,تشقق"
                        },
                        new
                        {
                            DiseaseId = 20,
                            Description = "مرض جلدي مناعي",
                            Name = "Psoriasis",
                            NameArabic = "صدفية",
                            Severity = "Moderate",
                            Symptoms = "red patches,scales,itching,dry skin,cracked skin,بقع حمراء,قشور,حكة,جلد جاف,تشقق"
                        },
                        new
                        {
                            DiseaseId = 21,
                            Description = "حالة جلدية شائعة",
                            Name = "Acne",
                            NameArabic = "حب الشباب",
                            Severity = "Mild",
                            Symptoms = "pimples,blackheads,oily skin,scarring,بثور,رؤوس سوداء,جلد دهني,ندوب"
                        },
                        new
                        {
                            DiseaseId = 22,
                            Description = "ارتفاع ضغط الدم",
                            Name = "Hypertension",
                            NameArabic = "ضغط دم مرتفع",
                            Severity = "Severe",
                            Symptoms = "headache,dizziness,chest pain,shortness of breath,nosebleed,صداع,دوخة,ألم صدر,ضيق تنفس,نزيف أنف"
                        },
                        new
                        {
                            DiseaseId = 23,
                            Description = "أعراض مرض السكري",
                            Name = "Diabetes Symptoms",
                            NameArabic = "أعراض السكري",
                            Severity = "Severe",
                            Symptoms = "increased thirst,frequent urination,fatigue,blurred vision,slow healing,عطش شديد,تبول متكرر,تعب,زغللة,بطء التئام"
                        },
                        new
                        {
                            DiseaseId = 24,
                            Description = "نقص خلايا الدم الحمراء",
                            Name = "Anemia",
                            NameArabic = "فقر دم",
                            Severity = "Moderate",
                            Symptoms = "fatigue,weakness,pale skin,dizziness,shortness of breath,cold hands,تعب,ضعف,شحوب,دوخة,ضيق تنفس,برودة يدين"
                        },
                        new
                        {
                            DiseaseId = 25,
                            Description = "اضطراب القلق",
                            Name = "Anxiety",
                            NameArabic = "قلق",
                            Severity = "Moderate",
                            Symptoms = "worry,nervousness,rapid heartbeat,sweating,trembling,fatigue,قلق,توتر,خفقان,تعرق,رجفة,تعب"
                        },
                        new
                        {
                            DiseaseId = 26,
                            Description = "اضطراب النوم",
                            Name = "Insomnia",
                            NameArabic = "أرق",
                            Severity = "Mild",
                            Symptoms = "difficulty sleeping,waking up,fatigue,irritability,صعوبة نوم,استيقاظ,تعب,عصبية"
                        },
                        new
                        {
                            DiseaseId = 27,
                            Description = "نقص السوائل في الجسم",
                            Name = "Dehydration",
                            NameArabic = "جفاف",
                            Severity = "Moderate",
                            Symptoms = "thirst,dry mouth,fatigue,dizziness,dark urine,عطش,جفاف فم,تعب,دوخة,بول داكن"
                        },
                        new
                        {
                            DiseaseId = 28,
                            Description = "التهاب في المفاصل",
                            Name = "Arthritis",
                            NameArabic = "التهاب المفاصل",
                            Severity = "Moderate",
                            Symptoms = "joint pain,stiffness,swelling,reduced movement,ألم مفاصل,تيبس,تورم,صعوبة حركة"
                        },
                        new
                        {
                            DiseaseId = 29,
                            Description = "التهاب غشاء العين",
                            Name = "Conjunctivitis",
                            NameArabic = "التهاب الملتحمة",
                            Severity = "Mild",
                            Symptoms = "red eyes,itching,discharge,tearing,burning,احمرار عين,حكة,إفرازات,دموع,حرقة"
                        });
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WorkingHours")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DoctorId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.MedicalRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Prescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RecordId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<string>("ActiveIngredient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MedicineId");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            MedicineId = 1,
                            ActiveIngredient = "Paracetamol",
                            Category = "Pain Relief",
                            Description = "مسكن للألم وخافض للحرارة",
                            DosageForm = "Tablets",
                            GenericName = "Acetaminophen",
                            ImageUrl = "/images/medicines/paracetamol.jpg",
                            IsAvailable = true,
                            Name = "Paracetamol",
                            Price = 3.50m,
                            Strength = "500mg"
                        },
                        new
                        {
                            MedicineId = 2,
                            ActiveIngredient = "Ibuprofen",
                            Category = "Pain Relief",
                            Description = "مضاد التهاب ومسكن",
                            DosageForm = "Tablets",
                            GenericName = "Ibuprofen",
                            ImageUrl = "/images/medicines/ibuprofen.jpg",
                            IsAvailable = true,
                            Name = "Ibuprofen",
                            Price = 5.00m,
                            Strength = "400mg"
                        },
                        new
                        {
                            MedicineId = 3,
                            ActiveIngredient = "Aspirin",
                            Category = "Pain Relief",
                            Description = "مسكن ومضاد التهاب",
                            DosageForm = "Tablets",
                            GenericName = "Aspirin",
                            ImageUrl = "/images/medicines/aspirin.jpg",
                            IsAvailable = true,
                            Name = "Aspirin",
                            Price = 2.50m,
                            Strength = "100mg"
                        },
                        new
                        {
                            MedicineId = 4,
                            ActiveIngredient = "Amoxicillin",
                            Category = "Antibiotics",
                            Description = "مضاد حيوي واسع الطيف",
                            DosageForm = "Capsules",
                            GenericName = "Amoxicillin",
                            ImageUrl = "/images/medicines/amoxicillin.jpg",
                            IsAvailable = true,
                            Name = "Amoxicillin",
                            Price = 8.50m,
                            Strength = "500mg"
                        },
                        new
                        {
                            MedicineId = 5,
                            ActiveIngredient = "Azithromycin",
                            Category = "Antibiotics",
                            Description = "مضاد حيوي قوي",
                            DosageForm = "Tablets",
                            GenericName = "Azithromycin",
                            ImageUrl = "/images/medicines/azithromycin.jpg",
                            IsAvailable = true,
                            Name = "Azithromycin",
                            Price = 12.00m,
                            Strength = "250mg"
                        },
                        new
                        {
                            MedicineId = 6,
                            ActiveIngredient = "Omeprazole",
                            Category = "Digestive Health",
                            Description = "لعلاج حموضة المعدة",
                            DosageForm = "Capsules",
                            GenericName = "Omeprazole",
                            ImageUrl = "/images/medicines/omeprazole.jpg",
                            IsAvailable = true,
                            Name = "Omeprazole",
                            Price = 6.00m,
                            Strength = "20mg"
                        },
                        new
                        {
                            MedicineId = 7,
                            ActiveIngredient = "Aluminum Hydroxide",
                            Category = "Digestive Health",
                            Description = "معادل للحموضة",
                            DosageForm = "Syrup",
                            GenericName = "Antacid",
                            ImageUrl = "/images/medicines/antacid.jpg",
                            IsAvailable = true,
                            Name = "Antacid",
                            Price = 4.50m,
                            Strength = "200ml"
                        },
                        new
                        {
                            MedicineId = 8,
                            ActiveIngredient = "Loperamide",
                            Category = "Digestive Health",
                            Description = "لعلاج الإسهال",
                            DosageForm = "Tablets",
                            GenericName = "Loperamide",
                            ImageUrl = "/images/medicines/loperamide.jpg",
                            IsAvailable = true,
                            Name = "Loperamide",
                            Price = 5.50m,
                            Strength = "2mg"
                        },
                        new
                        {
                            MedicineId = 9,
                            ActiveIngredient = "Cetirizine",
                            Category = "Allergy Relief",
                            Description = "مضاد للهستامين",
                            DosageForm = "Tablets",
                            GenericName = "Cetirizine",
                            ImageUrl = "/images/medicines/cetirizine.jpg",
                            IsAvailable = true,
                            Name = "Cetirizine",
                            Price = 4.00m,
                            Strength = "10mg"
                        },
                        new
                        {
                            MedicineId = 10,
                            ActiveIngredient = "Loratadine",
                            Category = "Allergy Relief",
                            Description = "مضاد حساسية",
                            DosageForm = "Tablets",
                            GenericName = "Loratadine",
                            ImageUrl = "/images/medicines/loratadine.jpg",
                            IsAvailable = true,
                            Name = "Loratadine",
                            Price = 4.50m,
                            Strength = "10mg"
                        },
                        new
                        {
                            MedicineId = 11,
                            ActiveIngredient = "Salbutamol",
                            Category = "Respiratory",
                            Description = "موسع للشعب الهوائية",
                            DosageForm = "Inhaler",
                            GenericName = "Salbutamol",
                            ImageUrl = "/images/medicines/salbutamol.jpg",
                            IsAvailable = true,
                            Name = "Salbutamol",
                            Price = 15.00m,
                            Strength = "100mcg"
                        },
                        new
                        {
                            MedicineId = 12,
                            ActiveIngredient = "Dextromethorphan",
                            Category = "Respiratory",
                            Description = "شراب للسعال",
                            DosageForm = "Syrup",
                            GenericName = "Dextromethorphan",
                            ImageUrl = "/images/medicines/cough-syrup.jpg",
                            IsAvailable = true,
                            Name = "Cough Syrup",
                            Price = 6.50m,
                            Strength = "100ml"
                        },
                        new
                        {
                            MedicineId = 13,
                            ActiveIngredient = "Ascorbic Acid",
                            Category = "Vitamins",
                            Description = "فيتامين سي",
                            DosageForm = "Tablets",
                            GenericName = "Ascorbic Acid",
                            ImageUrl = "/images/medicines/vitaminc.jpg",
                            IsAvailable = true,
                            Name = "Vitamin C",
                            Price = 7.00m,
                            Strength = "1000mg"
                        },
                        new
                        {
                            MedicineId = 14,
                            ActiveIngredient = "Vitamin D3",
                            Category = "Vitamins",
                            Description = "فيتامين د",
                            DosageForm = "Capsules",
                            GenericName = "Cholecalciferol",
                            ImageUrl = "/images/medicines/vitamind.jpg",
                            IsAvailable = true,
                            Name = "Vitamin D",
                            Price = 8.00m,
                            Strength = "5000IU"
                        },
                        new
                        {
                            MedicineId = 15,
                            ActiveIngredient = "Mixed Vitamins",
                            Category = "Vitamins",
                            Description = "فيتامينات متعددة",
                            DosageForm = "Tablets",
                            GenericName = "Multivitamin",
                            ImageUrl = "/images/medicines/multivitamin.jpg",
                            IsAvailable = true,
                            Name = "Multivitamin",
                            Price = 10.00m,
                            Strength = "Daily"
                        });
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.TreatmentRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiseaseId")
                        .HasColumnType("int");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("MedicineId");

                    b.ToTable("TreatmentRecommendations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiseaseId = 1,
                            MedicineId = 1,
                            Priority = 9
                        },
                        new
                        {
                            Id = 2,
                            DiseaseId = 1,
                            MedicineId = 9,
                            Priority = 7
                        },
                        new
                        {
                            Id = 3,
                            DiseaseId = 1,
                            MedicineId = 13,
                            Priority = 6
                        },
                        new
                        {
                            Id = 4,
                            DiseaseId = 2,
                            MedicineId = 1,
                            Priority = 10
                        },
                        new
                        {
                            Id = 5,
                            DiseaseId = 2,
                            MedicineId = 2,
                            Priority = 8
                        },
                        new
                        {
                            Id = 6,
                            DiseaseId = 3,
                            MedicineId = 4,
                            Priority = 10
                        },
                        new
                        {
                            Id = 7,
                            DiseaseId = 3,
                            MedicineId = 12,
                            Priority = 8
                        },
                        new
                        {
                            Id = 8,
                            DiseaseId = 4,
                            MedicineId = 5,
                            Priority = 10
                        },
                        new
                        {
                            Id = 9,
                            DiseaseId = 4,
                            MedicineId = 1,
                            Priority = 7
                        },
                        new
                        {
                            Id = 10,
                            DiseaseId = 5,
                            MedicineId = 11,
                            Priority = 10
                        },
                        new
                        {
                            Id = 11,
                            DiseaseId = 6,
                            MedicineId = 6,
                            Priority = 10
                        },
                        new
                        {
                            Id = 12,
                            DiseaseId = 6,
                            MedicineId = 7,
                            Priority = 7
                        },
                        new
                        {
                            Id = 13,
                            DiseaseId = 7,
                            MedicineId = 8,
                            Priority = 9
                        },
                        new
                        {
                            Id = 14,
                            DiseaseId = 7,
                            MedicineId = 6,
                            Priority = 7
                        },
                        new
                        {
                            Id = 15,
                            DiseaseId = 8,
                            MedicineId = 8,
                            Priority = 9
                        },
                        new
                        {
                            Id = 16,
                            DiseaseId = 8,
                            MedicineId = 7,
                            Priority = 7
                        },
                        new
                        {
                            Id = 17,
                            DiseaseId = 10,
                            MedicineId = 6,
                            Priority = 10
                        },
                        new
                        {
                            Id = 18,
                            DiseaseId = 10,
                            MedicineId = 7,
                            Priority = 8
                        },
                        new
                        {
                            Id = 19,
                            DiseaseId = 11,
                            MedicineId = 1,
                            Priority = 9
                        },
                        new
                        {
                            Id = 20,
                            DiseaseId = 11,
                            MedicineId = 2,
                            Priority = 8
                        },
                        new
                        {
                            Id = 21,
                            DiseaseId = 12,
                            MedicineId = 2,
                            Priority = 10
                        },
                        new
                        {
                            Id = 22,
                            DiseaseId = 12,
                            MedicineId = 1,
                            Priority = 7
                        },
                        new
                        {
                            Id = 23,
                            DiseaseId = 13,
                            MedicineId = 2,
                            Priority = 10
                        },
                        new
                        {
                            Id = 24,
                            DiseaseId = 13,
                            MedicineId = 3,
                            Priority = 7
                        },
                        new
                        {
                            Id = 25,
                            DiseaseId = 14,
                            MedicineId = 9,
                            Priority = 10
                        },
                        new
                        {
                            Id = 26,
                            DiseaseId = 14,
                            MedicineId = 10,
                            Priority = 9
                        },
                        new
                        {
                            Id = 27,
                            DiseaseId = 15,
                            MedicineId = 9,
                            Priority = 10
                        },
                        new
                        {
                            Id = 28,
                            DiseaseId = 16,
                            MedicineId = 4,
                            Priority = 10
                        },
                        new
                        {
                            Id = 29,
                            DiseaseId = 17,
                            MedicineId = 4,
                            Priority = 10
                        },
                        new
                        {
                            Id = 30,
                            DiseaseId = 17,
                            MedicineId = 1,
                            Priority = 7
                        },
                        new
                        {
                            Id = 31,
                            DiseaseId = 18,
                            MedicineId = 5,
                            Priority = 9
                        },
                        new
                        {
                            Id = 32,
                            DiseaseId = 18,
                            MedicineId = 1,
                            Priority = 7
                        },
                        new
                        {
                            Id = 33,
                            DiseaseId = 24,
                            MedicineId = 15,
                            Priority = 9
                        },
                        new
                        {
                            Id = 34,
                            DiseaseId = 27,
                            MedicineId = 13,
                            Priority = 8
                        },
                        new
                        {
                            Id = 35,
                            DiseaseId = 28,
                            MedicineId = 2,
                            Priority = 10
                        },
                        new
                        {
                            Id = 36,
                            DiseaseId = 28,
                            MedicineId = 3,
                            Priority = 8
                        },
                        new
                        {
                            Id = 37,
                            DiseaseId = 29,
                            MedicineId = 4,
                            Priority = 9
                        });
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 31, 22, 27, 2, 120, DateTimeKind.Local).AddTicks(5701),
                            Email = "admin@healthcare.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$6IO4t1J7LRmVZabnPwtrye1MG8D/gKTeN7/fke8hu.ldwaIqO/pRe",
                            Phone = "0790000000",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.AIConversation", b =>
                {
                    b.HasOne("SmartHealthcareSystem.Models.User", "User")
                        .WithMany("AIConversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Appointment", b =>
                {
                    b.HasOne("SmartHealthcareSystem.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartHealthcareSystem.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Doctor", b =>
                {
                    b.HasOne("SmartHealthcareSystem.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("SmartHealthcareSystem.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.MedicalRecord", b =>
                {
                    b.HasOne("SmartHealthcareSystem.Models.Doctor", "Doctor")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartHealthcareSystem.Models.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Patient", b =>
                {
                    b.HasOne("SmartHealthcareSystem.Models.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("SmartHealthcareSystem.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.TreatmentRecommendation", b =>
                {
                    b.HasOne("SmartHealthcareSystem.Models.Disease", "Disease")
                        .WithMany("TreatmentRecommendations")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHealthcareSystem.Models.Medicine", "Medicine")
                        .WithMany("TreatmentRecommendations")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Disease", b =>
                {
                    b.Navigation("TreatmentRecommendations");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Medicine", b =>
                {
                    b.Navigation("TreatmentRecommendations");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("SmartHealthcareSystem.Models.User", b =>
                {
                    b.Navigation("AIConversations");

                    b.Navigation("Doctor")
                        .IsRequired();

                    b.Navigation("Patient")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
